name: easyml
dependencies:
- mkl=11.3.3=0
- numpy=1.11.2=py35_0
- openssl=1.0.2j=0
- pip=8.1.2=py35_0
- python=3.5.2=0
- readline=6.2=2
- setuptools=27.2.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - cycler==0.10.0
  - glmnet==1.0.0
  - matplotlib==1.5.3
  - pandas==0.19.0
  - pyparsing==2.1.10
  - python-dateutil==2.5.3
  - pytz==2016.7
  - scikit-learn==0.18
  - scipy==0.18.1
  - six==1.10.0
  - tqdm==4.9.0
